name: Run Tests on Push

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: configs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Access secrets
        run: echo "MONGO_APP_ID=${{ secrets.MONGO_APP_ID }} POSTGRES_APP_ID=${{ secrets.POSTGRES_APP_ID }}"
